# source: https://raw.githubusercontent.com/AdamWhitcroft/Apaxy/master/apaxy/htaccess.txt
archive:  7z bz2 cab gz tar
audio:    aac aif aifc aiff ape au flac iff m4a mid mp3 mpa ra wav wma f4a f4b oga ogg xm it s3m mod
bin:      bin hex
bmp:      bmp
c:        c
calc:     xlsx xlsm xltx xltm xlam xlr xls csv
cpp:      cpp
css:      css sass scss
deb:      deb
doc:      doc docx docm dot dotx dotm log msg odt pages rtf tex wpd wps
draw:     svg svgz
eps:      ai eps
exe:      exe
gif:      gif
h:        h
html:     html xhtml shtml htm URL url
ico:      ico
java:     jar
jpg:      jpg jpeg jpe
js:       js json
markdown: md
package:  pkg dmg
pdf:      pdf
php:      php phtml
playlist: m3u m3u8 pls pls8
png:      png
ps:       ps
psd:      psd
py:       py
rar:      rar
rb:       rb
rpm:      rpm
rss:      rss
script:   bat cmd sh
sql:      sql
tiff:     tiff tif
text:     txt nfo
video:    asf asx avi flv mkv mov mp4 mpg rm srt swf vob wmv m4v f4v f4p ogv
xml:      xml
zip:      zip
