#!/usr/bin/env ruby

APP_PATH = File.expand_path('../../config/application',  __FILE__)
require File.expand_path('../../config/environment',  __FILE__)


server = Server.find(1)

# read file list from stdin
$stdin.each_line do |path|
  server.resources.create! :path => path.strip
end

